### ISSUE TITLE
Missing Recipes 1.17.1

### ISSUE THREAD

**Issue by dittymargoo** [German-Immersive-Railroading-Community/GIRC-Redstone#27]
Mod version for 1.17.1 : GIRC-Redstone-1.0.141.jar  Installed using Curseforge launcher.

I seem to be missing recipes for your mod.  JEI is displaying the items for your mod but no recipes. I cannot use the recipes that are shown in Curseforge website images either.

I added your mod to an existing world (85 mods total).  I've reloaded minecraft twice but it still doesn't give me the ability to craft the items.  I've checked for any required dependencies too.  Am I missing something?  Are there any known mods that could cause this to happen?  

As a test I'm downgrading to GIRC-Redstone-1.0.95.jar

**Comment by dittymargoo** [comment]
I've downgraded to GIRC-Redston-1.0.95.jar - but still no recipes and I've tested in creative on this version.  The items that can be placed in the world do not have a texture but the linking torch works.  If it's a conflict with another mod then I'm stumped as to which one without deleting everything and starting again.

I'm afraid I'll have to uninstall.  But I loved the idea of your mod and sad that it's not working for me.

**Comment by MrTroble** [comment]
Hello @dittymargoo it is unlikely to be an issue with an other mod we are investigating the issue thanks for your report

**Comment by MrTroble** [comment]
We have identified and mitigated the issue, it has been there for a while now and nobody reported it so far. So thank you very much for reporting this issue. We have extended our test setup to newer versions.

Cheers and sorry for the inconvenience,
~MrTroble

**Comment by MrTroble** [comment]
The new version should be out any minute

**Comment by dittymargoo** [comment]
Thank you so much for doing this.  I thought it might have been something I was missing.

**Comment by MrTroble** [comment]
Your welcome,

please notify us if there should be further issues

Cheers
~MrTroble
