### ISSUE TITLE
Link Multiple Acceptors

### ISSUE THREAD

**Issue by RyonGerringer** [German-Immersive-Railroading-Community/GIRC-Redstone#291]
Currently have to manually click each acceptor. It would be nice to have a "Multi-Linker" to go down a line of acceptors, link them all to a multi-emitter. Instead of going back and forth between lots of acceptors. 👍

**Comment by MrTroble** [comment]
Yeah I have already thought of that and I agree that it is a good idea. Thank your for your suggestion if we find some time we will implement it.

Cheers
~MrTroble

**Comment by Jeronimo97** [comment]
We have added a Multi-Linker Tool to the mod in the latest version. (v3.2.1)
