### ISSUE TITLE
Linking a previously linked Acceptor Bug

### ISSUE THREAD

**Issue by RyonGerringer** [German-Immersive-Railroading-Community/GIRC-Redstone#292]
When linking a previously linked acceptor. The linker does not delete the old link, yet it will be set to link to the acceptor indefinitely, until destroying the linker.

**Comment by Uhutown** [comment]
Good Morning,
Did you tried to press shift + right klick. Normaly this should reset the linker.

**Comment by RyonGerringer** [comment]
Thanks for the quick reply! It worked.

**Comment by MrTroble** [comment]
We could maybe add some more information in item information to indicate that behaviour? Idk. any suggestions on how to make this more intuitive?
