### ISSUE TITLE
Any plans to port to Fabric?

### ISSUE THREAD

**Issue by malino24** [German-Immersive-Railroading-Community/GIRC-Redstone#327]
see title

**Comment by MrTroble** [comment]
We currently do not plan to port this mod to fabric however if you want to help with porting efforts, we are always open for PRs.

**Comment by Jeronimo97** [comment]
Hey, we are currently working on creating a fabric port. :)

**Comment by Jeronimo97** [comment]
@malino-dev 
I have just released the Fabric versions, although with a little delay. 🙈 

https://www.curseforge.com/minecraft/mc-mods/tc-wireless-redstone/files/all?page=1&pageSize=20
