### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by PongoSapiens** [German-Immersive-Railroading-Community/GIRC-Redstone#362]
On a server this mod is constantly spamming the console with lines of the form:
List: [BlockPos{x=-32, y=57, z=6}, BlockPos{x=12, y=57, z=-103}, BlockPos{x=-12, y=57, z=5}]
Comp: {linkedPos:[{X:-32,Y:57,Z:6},{X:12,Y:57,Z:-103},{X:-12,Y:57,Z:5}]}

This looks like debugging to me, and it's renders the console hard to use.

Thanks.

Pongo

**Comment by PongoSapiens** [comment]
This looks to have been fixed in the source but not released (at least not for forge/1.20.1). A release would make me happy :)

Pongo

**Comment by Jeronimo97** [comment]
Hey, it was removed for 1.20.4 because that's the current version. Other 1.20.x versions are outdated because 1.20.4 is usually the more recent version of Minecraft. 

But I will take a look at it.

**Comment by PongoSapiens** [comment]
Thank you
