### ISSUE TITLE
Blocks do not drop when broken

### ISSUE THREAD

**Issue by Saereth** [German-Immersive-Railroading-Community/GIRC-Redstone#81]
Breaking the emitter or acceptor does not give back the mined block it just destroys it. forge v1.18.2

**Comment by MrTroble** [comment]
Thank your for your report, we will investigate

**Comment by MrTroble** [comment]
Sorry for the long response time, blocks should drop with an iron pickaxe with the next update

**Comment by Saereth** [comment]
thanks alot!

**Comment by MrTroble** [comment]
Closed with #82, update should be out in some minutes
